#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020-2022 Re
#
# https://game.naruto.re
#

name = 'NarakaPath'
hp = 20000
hpBar.y = 83
speed = 224
isArmored = true

[Idle]
frame = [
    'NarakaPath_Idle_01',
]

[Walk]
frame = [
    'NarakaPath_Walk_01',
    'NarakaPath_Walk_02',
    'NarakaPath_Walk_03',
    'NarakaPath_Walk_04',
    'NarakaPath_Walk_05',
    'NarakaPath_Walk_06',
]

[Hurt]
frame = [
    'NarakaPath_Hurt_01',
    'setDelay = 10',
    'NarakaPath_Hurt_02',
]

[AirHurt]
frame = [
    'NarakaPath_AirHurt_01',
]

[Knockdown]
frame = [
    'NarakaPath_Knockdown_01',
    'setDelay = 10',
    'NarakaPath_Knockdown_02',
    'setDelay = 60',
    'NarakaPath_Knockdown_03',
    'NarakaPath_Knockdown_04',
    'NarakaPath_Knockdown_05',
]

[Float]
frame = [
    'NarakaPath_Float_01',
    'setDelay = 10',
    'NarakaPath_Float_02',
    'setDelay = 10',
    'NarakaPath_Float_03',
]

[Dead]
frame = [
    'NarakaPath_Knockdown_01',
    'NarakaPath_Knockdown_02',
]

[NAttack]
type = 'nAttack'
value = 150
rangeX = 0
rangeY = 16
frame = [
    'NarakaPath_NAttack_01',
    'NarakaPath_NAttack_02',
    'NarakaPath_NAttack_03',
    'setSound = Audio/Effect/combo1.ogg',
    'setHit = n_hit',
    'NarakaPath_NAttack_04',
    'NarakaPath_NAttack_05',
    'NarakaPath_NAttack_06',
    'NarakaPath_NAttack_07',
    'setMove = 8',
    'NarakaPath_NAttack_08',
    'setSound = Audio/Effect/combo2.ogg',
    'setHit = n_hit',
    'NarakaPath_NAttack_09',
    'NarakaPath_NAttack_10',
    'NarakaPath_NAttack_11',
    'NarakaPath_NAttack_12',
    'setSound = Audio/Pain/NarakaPath_combo.ogg',
    'setMove = 16',
    'NarakaPath_NAttack_13',
    'setHit = l_hit',
    'setSound = Audio/Effect/combo3.ogg',
    'NarakaPath_NAttack_14',
]

[Skill01]
type = 'sBuff'
rangeX = 0
rangeY = 15
cd = 1
frame = [
    'setSound = Audio/Pain/NarakaPath_skill1.ogg',
    'NarakaPath_Skill01_01',
    'setDelay = 10',
    'NarakaPath_Skill01_02',
    'setSkillEffect = Kujiyose',
    'setClone = 0',
    'setDelay = 50',
]

[Skill02]
type = 'abAttack'
value = 1500
rangeX = 192
rangeY = 64
cd = 1
frame = [
    'setSound = Audio/Pain/NarakaPath_skill2.ogg',
    'NarakaPath_Skill01_01',
    'setDelay = 10',
    'NarakaPath_Skill01_02',
    'setSkillEffect = Kujiyose',
    'setClone = -1',
    'setDelay = 50',
]

[Skill03]
type = 'aAttack'
value = 500
rangeX = 160
rangeY = 64
cd = 25
frame = [
    'Pain_Skill03_01',
    'setSound = Audio/Pain/Pain_skill3.ogg',
    'setCmd = setInvincible',
    'Pain_Skill03_02',
    'Pain_Skill03_03',
    'Pain_Skill03_04',
    'setHit = n_hit',
    'setDelay = 10',
    'Pain_Skill03_05',
    'setHit = n_hit',
    'setDelay = 10',
    'Pain_Skill03_06',
    'setHit = n_hit',
    'setDelay = 10',
    'Pain_Skill03_07',
    'setHit = n_hit',
    'setDelay = 10',
    'setCmd = reInvincible',
]
[Skill04]
type = 'oAttack'
value = 450
rangeX = 65
rangeY = 65
frame = [
    'Pain_Skill02_01',
    'setSound = Audio/Pain/Pain_skill2.ogg',
    'setDelay = 10',
    'Pain_Skill02_02',
    'setDelay = 10',
    'Pain_Skill02_03',
    'setHit = ab_hit',
    'Pain_Skill02_04',
    'Pain_Skill02_05',
    'Pain_Skill02_06',
    
    'setSound = Audio/Effect/ougis.ogg',
    'Pain_Skill04_01',
    'setFont = dbtx',
    'setDelay = 20',
    'setSound = Audio/Pain/Pain_skill4.ogg',
    'setSkill = Jibaku',
    'setDelay = 30',
    'Pain_Skill04_02',
    'setFont = ka',
    'setDelay = 10',
    'Pain_Skill04_03',
    'setDelay = 10',
]
    
[Spc01]
type = 'aAttack'
value = 300
rangeX = 32
rangeY = 48
frame = [
    'NarakaPath_Hurt_01',
    'setHit = c_hit',
    'setDelay = 10',
    'NarakaPath_Hurt_02',
    'setHit = c_hit',
]
