name = 'Suigetsu'
hp = 7500
hpBar.y = 70
speed = 224

[Idle]
frame = [
    'Suigetsu_Idle_01',
    'Suigetsu_Idle_02',
    'Suigetsu_Idle_03',
    'Suigetsu_Idle_04',
]

[Walk]
frame = [
    'Suigetsu_Walk_01',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_02',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_03',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_04',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_05',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_06',
]

[Hurt]
frame = [
    'setMove = 32',
    'Suigetsu_Hurt_01',
    'Suigetsu_Hurt_02',
    'Suigetsu_Hurt_03',
    'setDSound = Audio/Suigetsu/suigetsu_hurt.ogg',
]

[AirHurt]
frame = ['Suigetsu_AirHurt_01']

[Knockdown]
frame = [
    'Suigetsu_KnockDown_01',
    'setDelay = 10',
    'Suigetsu_KnockDown_02',
    'setDelay = 60',
    'Suigetsu_KnockDown_03',
    'Suigetsu_KnockDown_04',
    'Suigetsu_KnockDown_05',
    'Suigetsu_KnockDown_06',
]

[Float]
frame = [
    'Suigetsu_Float_01',
    'setDelay = 10',
    'Suigetsu_Float_02',
    'setDelay = 10',
    'Suigetsu_Float_03',
]

[Dead]
frame = [
    'Suigetsu_KnockDown_01',
    'Suigetsu_KnockDown_02',
    'setDSound = Audio/Suigetsu/suigetsu_dead.ogg',
]

[NAttack]

type = 'spBuff'
value = 80
rangeX = 0
rangeY = 16
cd = 0

frame = [
    'Suigetsu_NAttack_01',
    'Suigetsu_NAttack_02',
    'Suigetsu_NAttack_03',
    'setHit = n_hit',
    'setDSound = Audio/Effect/combo1.ogg',
    'Suigetsu_NAttack_04',
    'Suigetsu_NAttack_05',
    'Suigetsu_NAttack_06',
    'setHit = n_hit',
    'Suigetsu_NAttack_07',
    'Suigetsu_NAttack_08',
    'Suigetsu_NAttack_09',
    'setHit = n_hit',
    'setDSound = Audio/Effect/combo2.ogg',
    'Suigetsu_NAttack_10',
    'Suigetsu_NAttack_11',
    'Suigetsu_NAttack_12',
    'setHit = n_hit',
    'setMove = 16',
    'Suigetsu_NAttack_13',
    'setDSound = Audio/Suigetsu/suigetsu_combo.ogg',
    'Suigetsu_NAttack_14',
    'Suigetsu_NAttack_15',
    'setHit = n_hit',
    'setDelay = 20',
    'Suigetsu_Skill02_05',
    'Suigetsu_Skill02_06',
    'Suigetsu_Skill02_07',
    'setSkill = Kubi',
    #  <!--水月扔出Kubi后变成另一种形态-->
    'setDelay = 20',
    'setBuff = 17',
]

[Skill01]

type = 'cAttack'
value = 160
rangeX = 64
rangeY = 48
cd = 10

frame = [
    'Suigetsu_Skill01_01',
    'setDSound = Audio/Suigetsu/suigetsu_skill1.ogg',
    'setDelay = 10',
    'Suigetsu_Skill01_02',
    'setHit = o_hit',
    'Suigetsu_Skill01_03',
    'setChargeB = 128',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'Suigetsu_Skill01_04',
    'setHit = ct_hit',
    'setChargeB = 140',
    'Suigetsu_Skill01_04',
    'setHit = b_hit',
]

[Skill02]

type = 'aAttack'
value = 480
rangeX = 128
rangeY = 16
cd = 15

frame = [
    'setDSound = Audio/Effect/ougis.ogg',
    'setCmd = setInvincible',
    'setCmd = findTarget',
    'Suigetsu_Skill03_01',
    'Suigetsu_Skill03_02',
    'Suigetsu_Skill03_03',
    'Suigetsu_Skill03_04',
    'Suigetsu_Skill03_05',
    'setCmd = setTransport',
    'Suigetsu_Skill02_01',
    'setFlipped = 10',
    'setDSound = Audio/Suigetsu/suigetsu_skill2.ogg',
    'Suigetsu_Skill02_02',
    'setHit = ct_hit',
    'setChargeB = -220',
    'Suigetsu_Skill02_03',
    'Suigetsu_Skill02_04',
    'Suigetsu_Skill02_05',
    'Suigetsu_Skill02_06',
    'Suigetsu_Skill02_07',
    'setSkill = Kubi',
    'setDelay = 10',
    'Suigetsu_Skill02_07',
    'setSkill = Kubi',
    'setDelay = 10',
    'Suigetsu_Skill02_07',
    'setSkill = Kubi',
    'setDelay = 10',
    'Suigetsu_Skill02_07',
    'setSkill = Kubi',
    'setDelay = 10',
    'Suigetsu_Skill02_07',
    'setSkill = Kubi',
    'setDelay = 10',
    'setCmd = setTransport',
    'Suigetsu_Skill03_05',
    'Suigetsu_Skill03_04',
    'Suigetsu_Skill03_03',
    'Suigetsu_Skill03_02',
    'Suigetsu_Skill03_01',
    'Suigetsu_Skill02_08',
    'Suigetsu_Skill02_09',
    'Suigetsu_Skill02_10',
    'setCmd = reInvincible',
]

[Skill03]

type = 'aAttack'
value = 700
rangeX = 128
rangeY = 25
cd = 25

frame = [
    'setDSound = Audio/Suigetsu/suigetsu_skill4.ogg',
    'setFont = stp',
    'Suigetsu_Skill04_01',
    'setHit = ct_hit',
    'Suigetsu_Skill04_02',
    'Suigetsu_Skill04_03',
    'Suigetsu_Skill04_04',
    'setSkill = WaterBullet',
    'Suigetsu_Skill04_02',
    'Suigetsu_Skill04_03',
    'Suigetsu_Skill04_04',
    'setFont = kurae',
    'setSkill = WaterBullet',
    'Suigetsu_Skill04_02',
    'setDelay = 3',
    'Suigetsu_Skill04_05',
    'setFont = dokong',
    'setSkill = WaterBom',
    'setDelay = 0',
]

[Skill04]

type = 'aAttack'
value = 500
rangeX = 64
rangeY = 64
cd = 1

frame = [
    'setHit = o2_hit',
    'setCmd = setCounter',
    'setDSound = Audio/Suigetsu/suigetsu_skill3_1.ogg',
    'Suigetsu_Skill05_07',
    'setHit = c_hit',
    'Suigetsu_Skill05_08',
    'setChargeB = 128',
    'Suigetsu_Skill05_10',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_4.ogg',
    'setHit = c_hit',
    'Suigetsu_Skill05_11',
    'setHit = c_hit',
    'Suigetsu_Skill05_12',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'setHit = o_hit',
    'Suigetsu_Skill05_13',
    'setHit = c_hit',
    'Suigetsu_Skill05_16',
    'setChargeB = 96',
    'Suigetsu_Skill05_17',
    'setShadow = 10',
    'Suigetsu_Skill05_18',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_3.ogg',
    'setHit = c_hit',
    'Suigetsu_Skill05_19',
    'setHit = c_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'Suigetsu_Skill05_20',
    'setHit = c_hit',
    'Suigetsu_Skill05_22',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_23',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_24',
    'setShadow = 10',
    'setHit = f2_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'Suigetsu_Skill05_25',
    'setShadow = 10',
    'setHit = c_hit',
    'setHit = f_hit',
    'Suigetsu_Skill05_26',
    'setShadow = 10',
    'setHit = ac_hit',
    'Suigetsu_Skill05_27',
    'setHit = c_hit',
    'Suigetsu_Skill05_28',
    'setHit = c_hit',
    'setChargeB = 48',
    'Suigetsu_Skill05_29',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_30',
    'setShadow = 10',
    'setHit = c_hit',
    'setHit = ac_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'Suigetsu_Skill05_31',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_32',
    'setHit = c_hit',
    'Suigetsu_Skill05_33',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_34',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_35',
    'setShadow = 10',
    'setHit = c_hit',
    'setChargeB = 48',
    'setHit = ac_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'Suigetsu_Skill05_36',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_37',
    'setHit = c_hit',
    'Suigetsu_Skill05_38',
    'setHit = c_hit',
    'Suigetsu_Skill05_50',
    'setJump = true',
    'Suigetsu_Skill05_51',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_52',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_53',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_54',
    'setShadow = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_55',
    'setShadow = 10',
    'setHit = c_hit',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_5.ogg',
    'setDelay = 10',
    'setHit = c_hit',
    'Suigetsu_Skill05_56',
    'setHit = c_hit',
    'Suigetsu_Skill05_57',
    'setHit = c_hit',
    'Suigetsu_Skill05_58',
    'setHit = f_hit',
    'Suigetsu_Skill05_59',
    'setHit = c_hit',
    'Suigetsu_Skill05_60',
    'setHit = c_hit',
]

[Skill05]

type = 'aAttack'
value = 760
rangeX = 128
rangeY = 48
cd = 1

frame = [
    'setDSound = Audio/Effect/ougis.ogg',
    'Suigetsu_Skill05_01',
    'Suigetsu_Skill05_02',
    'Suigetsu_Skill05_03',
    'Suigetsu_Skill05_04',
    'setCmd = setInvincible',
    'setCmd = findTarget',
    'setCmd = setTransport',
    'setHit = ct_hit',
    'setChargeB = -220',
    'Suigetsu_Skill05_05',
    'Suigetsu_Skill05_06',
    'setOugis = 10',
    'Suigetsu_Skill05_07',
    'Suigetsu_Skill05_08',
    'setChargeB = 128',
    'Suigetsu_Skill05_10',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_4.ogg',
    'setHit = c_hit',
    'Suigetsu_Skill05_11',
    'Suigetsu_Skill05_12',
    'setCmd = reInvincible',
    #  <!--第一段伤害后取消无敌状态-->
    'setDSound = Audio/Effect/blade_damage.ogg',
    'setHit = o_hit',
    'Suigetsu_Skill05_13',
    'Suigetsu_Skill05_16',
    'setChargeB = 96',
    'Suigetsu_Skill05_17',
    'setShadow = 10',
    'Suigetsu_Skill05_18',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_3.ogg',
    'setHit = c_hit',
    'Suigetsu_Skill05_19',
    'setHit = c_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'Suigetsu_Skill05_20',
    'Suigetsu_Skill05_22',
    'setShadow = 10',
    'Suigetsu_Skill05_23',
    'setShadow = 10',
    'Suigetsu_Skill05_24',
    'setShadow = 10',
    'setHit = fb_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'Suigetsu_Skill05_25',
    'setShadow = 10',
    'setHit = fb_hit',
    'Suigetsu_Skill05_26',
    'setShadow = 10',
    'setHit = ac_hit',
    'Suigetsu_Skill05_27',
    'Suigetsu_Skill05_28',
    'setChargeB = 48',
    'Suigetsu_Skill05_29',
    'setShadow = 10',
    'Suigetsu_Skill05_30',
    'setShadow = 10',
    'setHit = ac_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'Suigetsu_Skill05_31',
    'setShadow = 10',
    'Suigetsu_Skill05_32',
    'Suigetsu_Skill05_33',
    'setShadow = 10',
    'Suigetsu_Skill05_34',
    'setShadow = 10',
    'Suigetsu_Skill05_35',
    'setShadow = 10',
    'setChargeB = 48',
    'setHit = ac_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'Suigetsu_Skill05_36',
    'setShadow = 10',
    'Suigetsu_Skill05_37',
    'Suigetsu_Skill05_38',
    'Suigetsu_Skill05_50',
    'setJump = true',
    'Suigetsu_Skill05_51',
    'setShadow = 10',
    'Suigetsu_Skill05_52',
    'setShadow = 10',
    'Suigetsu_Skill05_53',
    'setShadow = 10',
    'Suigetsu_Skill05_54',
    'setShadow = 10',
    'Suigetsu_Skill05_55',
    'setShadow = 10',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_5.ogg',
    'setDelay = 10',
    'Suigetsu_Skill05_56',
    'Suigetsu_Skill05_57',
    'Suigetsu_Skill05_58',
    'setHit = f_hit',
    'Suigetsu_Skill05_59',
    'setCmd = setCounter',
    'Suigetsu_Skill05_60',
]

[Spc01]
anim = { base = 'Idle' }
frame = ['Suigetsu_Skill03_06']

[Spc02]
anim = { base = 'Walk' }
frame = [
    'Suigetsu_Skill03_06',
    'setMove = 18',
    'Suigetsu_Skill03_05',
    'setMove = 18',
    'Suigetsu_Walk_01',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_02',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_03',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_04',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_05',
    'setShadow = 10',
    'setMove = 2',
    'Suigetsu_Walk_06',
    'Suigetsu_Skill03_04',
    'setMove = 8',
    'Suigetsu_Skill03_05',
    'setMove = 18',
    'Suigetsu_Skill03_06',
    'setMove = 16',
]

[Spc03]

type = 'aAttack'
value = 90
rangeX = 10
rangeY = 32
cd = 0
frame = [
    'Suigetsu_Skill03_06',
    'Suigetsu_Skill03_08',
    'setHit = f2_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'setActionResume = 20',
    'setDSound = Audio/Suigetsu/suigetsu_skill3_2.ogg',
    'Suigetsu_Skill03_09',
    'setShadow = 10',
    'setJump = true',
    'Suigetsu_Skill03_10',
    'setShadow = 10',
    'setDelay = 2',
    'Suigetsu_Skill03_11',
    'setDelay = 2',
    'Suigetsu_Skill03_12',
    'setDelay = 10',
    'Suigetsu_Skill03_13',
    'setShadow = 10',
    'setHit = ac_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'setChargeB = 280',
    'setHit = ac_hit',
    'Suigetsu_Skill05_37',
    'setShadow = 10',
    'Suigetsu_Skill05_38',
    'setHit = ac_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'Suigetsu_Skill05_50',
    'setHit = ac_hit',
    'setFlipped = 10',
    'setHit = o2_hit',
    'Suigetsu_Skill05_51',
    'setShadow = 10',
    'Suigetsu_Skill05_52',
    'setShadow = 10',
    'setChargeB = 120',
    'setHit = o_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'setChargeB = 20',
    'Suigetsu_Skill05_53',
    'setShadow = 10',
    'Suigetsu_Skill05_54',
    'setHit = o_hit',
    'setDSound = Audio/Effect/blade_damage.ogg',
    'setChargeB = 50',
    'Suigetsu_Skill05_55',
    'setShadow = 10',
    'setDSound = Audio/Suigetsu/suigetsu_skill5_5.ogg',
    'Suigetsu_Skill05_56',
    'setShadow = 10',
    'setHit = o_hit',
    'Suigetsu_Skill05_57',
    'setChargeB = 60',
    'setHit = o_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'Suigetsu_Skill05_58',
    'setShadow = 10',
    'setHit = b_hit',
    'Suigetsu_Skill05_59',
    'setHit = f2_hit',
    'setDSound = Audio/Effect/blade_damage2.ogg',
    'Suigetsu_Skill05_60',
    'setShadow = 10',
    'setCmd = setCounter',
]
