#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020-2022 Re
#
# https://game.naruto.re
#

name = 'ObitoFrog'
hp = 10000
hpBar.y = 40
speed = 160

[Idle]
frame = [
    'ObitoFrog_Idle_01',
    'ObitoFrog_Walk_01',
]

[Walk]
frame = [
    'ObitoFrog_Walk_01',
    'ObitoFrog_Walk_02',
    'setDelay = 10',
    'ObitoFrog_Walk_03',
    'setDelay = 10',
]

[Hurt]
frame = [
    'setMove = 32',
    'ObitoFrog_Knockdown_01',
]

[AirHurt]
frame = [
    'ObitoFrog_Knockdown_01',
]

[Knockdown]
frame = [
    'ObitoFrog_Knockdown_01',
    'ObitoFrog_Knockdown_02',
    'ObitoFrog_Knockdown_03',
    'setDelay = 10',
    'ObitoFrog_Knockdown_04',
    'setDelay = 60',
    'ObitoFrog_Idle_01',
]

[Float]
frame = [
    'ObitoFrog_Float_01',
    'setDelay = 10',
    'ObitoFrog_Knockdown_02',
    'setDelay = 20',
]

[Dead]
frame = [
    'ObitoFrog_Knockdown_01',
    'ObitoFrog_Knockdown_02',
    'ObitoFrog_Knockdown_03',
    'ObitoFrog_Knockdown_04',
]

[NAttack]
type = 'nAttack'
value = 60
rangeX = 8
rangeY = 8
frame = [
    'ObitoFrog_NAttack_01',
    'setDelay = 10',
    'ObitoFrog_NAttack_02',
    'setDelay = 10',
    'ObitoFrog_NAttack_03',
    'ObitoFrog_NAttack_04',
    'setHit = n_hit',
    'setDelay = 10',
]
