#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020-2022 Re
#
# https://game.naruto.re
#

name = 'Pain'
hp = 9000
hpBar.y = 83
speed = 228

[Idle]
frame = [
    'Pain_Idle_01',
    'Pain_Idle_02',
    'Pain_Idle_03',
    'Pain_Idle_04',
    'Pain_Idle_05',
    'Pain_Idle_06',
    'Pain_Idle_07',
    'Pain_Idle_08',
]

[Walk]
frame = [
    'Pain_Walk_01',
    'Pain_Walk_02',
    'Pain_Walk_03',
    'Pain_Walk_04',
    'Pain_Walk_05',
    'Pain_Walk_06',
]

[Hurt]
frame = [
    'setMove = 32',
    'Pain_Hurt_01',
    'Pain_Hurt_02',
    'Pain_Hurt_03',
    'setSound = Audio/Pain/Pain_hurt.ogg',
]

[AirHurt]
frame = [
    'Pain_AirHurt_01',
]

[Knockdown]
frame = [
    'Pain_Knockdown_01',
    'setDelay = 10',
    'Pain_Knockdown_02',
    'setDelay = 60',
    'Pain_Knockdown_03',
    'Pain_Knockdown_04',
    'Pain_Knockdown_05',
]

[Float]
frame = [
    'Pain_Float_01',
    'setDelay = 10',
    'Pain_Float_02',
    'setDelay = 10',
    'Pain_Float_03',
]

[Dead]
frame = [
    'Pain_Knockdown_01',
    'Pain_Knockdown_02',
    'setSound = Audio/Pain/Pain_dead.ogg',
]

[NAttack]
type = 'nAttack'
value = 100
rangeX = 36
rangeY = 32
cd = 5
frame = [
    'Pain_Skill03_01',
    'setSound = Audio/Pain/Pain_skill3.ogg',
    'Pain_Skill03_02',
    'Pain_Skill03_03',
    'Pain_Skill03_04',
    'setHit = o_hit',    
    'setHit = bl_hit',
    'setDelay = 1',
    'Pain_Skill03_05',
    'setHit = o_hit',
    'setHit = bl_hit',
    'setDelay = 1',
    'Pain_Skill03_06',
    'setHit = c_hit',
    'setHit = bl_hit',
    'setDelay = 1',
    'Pain_Skill03_07',
    'setHit = c_hit',
    'setHit = bl_hit',
    'setDelay = 1',

    'Pain_Skill03_01',
    'setSound = Audio/Pain/Pain_skill3.ogg',
    'Pain_Skill03_02',
    'Pain_Skill03_03',
    'Pain_Skill03_04',
    'setHit = o_hit',    
    'setHit = bl_hit',
    'setDelay = 1',
    'Pain_Skill03_05',
    'setHit = o_hit',
    'setHit = bl_hit',
    'setDelay = 1',
    'Pain_Skill03_06',
    'setHit = c_hit',
    'setHit = bl_hit',
    'setDelay = 1',
    'Pain_Skill03_07',
    'setHit = c_hit',
    'setHit = bl_hit',
    'setDelay = 1',

    'setCmd = setGainCKR',
]

[Skill01]
type = 'sBuff'
value = 500
rangeX = 58
rangeY = 48
cd = 18
frame = [
    'Pain_Skill01_01',
    'setSound = Audio/Pain/Pain_skill1.ogg',
    'Pain_Skill01_02',
    'Pain_Skill01_03',
    'Pain_Skill01_04',
    'setDelay = 10',
    'setBuff = 10',

    'Pain_Skill03_01',
    'setSound = Audio/Pain/Pain_skill3.ogg',
    'Pain_Skill03_02',
    'Pain_Skill03_03',
    'Pain_Skill03_04',
    'setHit = o_hit',    
    'setDelay = 3',
    'Pain_Skill03_05',
    'setHit = o_hit',
    'setDelay = 3',
    'Pain_Skill03_06',
    'setHit = o_hit',
    'setDelay = 3',
    'Pain_Skill03_07',
    'setHit = o_hit',
    'setHit = f_hit',
    'setDelay = 3',
]

[Skill02]
type = 'abAttack'
value = 255
rangeX = 64
rangeY = 52
cd = 18
frame = [
    'Pain_Skill02_01',
    'setSound = Audio/Pain/Pain_skill2.ogg',
    'setDelay = 6',
    'setHit = l_hit',
    'Pain_Skill02_02',
    'setHit = l_hit',
    'setDelay = 5',
    'Pain_Skill02_03',
    'setHit = l_hit',
    'Pain_Skill02_04',
    'setHit = l_hit',
    'Pain_Skill02_05',
    'setHit = l_hit',
    'Pain_Skill02_06',
    'setHit = f_hit',

    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
]

[Skill03]
type = 'aAttack'
value = 150
rangeX = 58
rangeY = 52
cd = 25
frame = [
    'Pain_Skill03_01',
    'setSound = Audio/Pain/Pain_skill3.ogg',
    'setCmd = setInvincible',
    'Pain_Skill03_02',
    'Pain_Skill03_03',
    'Pain_Skill03_04',
    'setHit = o_hit',    
    'setDelay = 4',
    'Pain_Skill03_05',
    'setHit = o_hit',
    'setDelay = 4',
    'Pain_Skill03_04',
    'setHit = o_hit',    
    'setDelay = 4',
    'Pain_Skill03_05',
    'setHit = o_hit',
    'setDelay = 4',
    'Pain_Skill03_04',
    'setHit = o_hit',    
    'setDelay = 4',
    'Pain_Skill03_05',
    'setHit = o_hit',
    'setDelay = 4',
    'Pain_Skill03_06',
    'setHit = o_hit',
    'setDelay = 4',
    'Pain_Skill03_07',
    'setHit = o_hit',
    'setHit = f_hit',
    'setDelay = 4',
    'setCmd = reInvincible',
]

[Skill04]
type = 'oAttack'
value = 225
rangeX = 64
rangeY = 48
frame = [
    'Pain_Skill02_01',
    'setSound = Audio/Pain/Pain_skill2.ogg',
    'setDelay = 8',
    'Pain_Skill02_02',
    'setDelay = 6',
    'setHit = l_hit',
    'Pain_Skill02_03',
    'setHit = l_hit',
    'Pain_Skill02_04',
    'setHit = l_hit',    
    'Pain_Skill02_05',
    'setHit = l_hit',
    'Pain_Skill02_06',
    
    'setSound = Audio/Effect/ougis.ogg',
    'Pain_Skill04_01',
    'setFont = dbtx',
    'setDelay = 20',
    'setSound = Audio/Pain/Pain_skill4.ogg',
    'setSkill = Jibaku',
    'setDelay = 30',
    'Pain_Skill04_02',
    'setFont = ka',
    'setDelay = 10',
    'Pain_Skill04_03',
    'setDelay = 10',
]

[Skill05]
type = 'oAttack'
value = 300
rangeX = 48
rangeY = 48
frame = [
    'setSound = Audio/Effect/ougis.ogg',
    'Pain_Skill05_01',
    'setCmd = setInvincible',
    'setSkillEffect = Kujiyose',
    'setDelay = 10',
    'Pain_Skill05_02',
    'setOugis = 10',
    'Pain_Skill05_03',
    'Pain_Skill05_04',
    'Pain_Skill05_05',
    'Pain_Skill05_12',
    'setDelay = 10',
    'Pain_Skill05_06',
    'Pain_Skill05_07',
    'Pain_Skill05_08',
    'Pain_Skill05_09',
    'Pain_Skill05_10',
    'setDelay = 10',
    'Pain_Skill05_11',
    'setDelay = 10',
    'setTransform = 40',
    'setCmd = reInvincible',

    'setCmd = addHP',

    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',    
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',    
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',  
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
    'setCmd = setGainCKR',
]
