#
# Copyright (C) 2013-2016 Zakume
# Copyright (C) 2020-2022 Re
#
# https://game.naruto.re
#

name = 'Kubi'

[Idle]
frame = ['Kubi_Move_01']

[NAttack]
type = 'aAttack'
value = 75
rangeX = 32
rangeY = 48
anim = { loop = true }
frame = [
    'Kubi_Move_01',
    'setHit = ab_hit',
    'setCharge = 32',
    'Kubi_Move_02',
    'setHit = ab_hit',
    'setCharge = 32',
    'setSound = Audio/Effect/SRK2.mp3',
    'Kubi_Move_03',
    'setHit = ab_hit',
    'setCharge = 32',
    'Kubi_Move_04',
    'setHit = ab_hit',
    'setCharge = -32',
    'Kubi_Move_03',
    'setHit = ab_hit',
    'setCharge = -32',
    'Kubi_Move_02',
    'setHit = ab_hit',
    'setCharge = -32',
    'Kubi_Move_01',
    'setHit = ab_hit',
    'setCharge = -32',
    'Kubi_Move_02',
    'setHit = b_hit',
    'setDestroy = 0',
]
